global:
  resolve_timeout: 5m
  slack_api_url: 'https://hooks.slack.com/services/YOUR_SLACK_WEBHOOK'

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'slack-notifications'
  routes:
    - match:
        severity: critical
      receiver: 'slack-critical'
      group_wait: 10s
      repeat_interval: 1h
    - match:
        severity: warning
      receiver: 'slack-warnings'
      group_wait: 30s
      repeat_interval: 4h

receivers:
  - name: 'slack-notifications'
    slack_configs:
      - channel: '#alerts'
        send_resolved: true
        title: '{{ template "slack.default.title" . }}'
        text: '{{ template "slack.default.text" . }}'
        footer: 'HR Analytics Monitoring'
        actions:
          - type: button
            text: 'View in Grafana'
            url: 'http://grafana:3000/d/alerts'
          - type: button
            text: 'View in Prometheus'
            url: 'http://prometheus:9090/alerts'

  - name: 'slack-critical'
    slack_configs:
      - channel: '#critical-alerts'
        send_resolved: true
        title: '{{ template "slack.default.title" . }}'
        text: '{{ template "slack.default.text" . }}'
        footer: 'HR Analytics Critical Alerts'
        actions:
          - type: button
            text: 'View in Grafana'
            url: 'http://grafana:3000/d/alerts'
          - type: button
            text: 'View in Prometheus'
            url: 'http://prometheus:9090/alerts'

  - name: 'slack-warnings'
    slack_configs:
      - channel: '#warnings'
        send_resolved: true
        title: '{{ template "slack.default.title" . }}'
        text: '{{ template "slack.default.text" . }}'
        footer: 'HR Analytics Warning Alerts'
        actions:
          - type: button
            text: 'View in Grafana'
            url: 'http://grafana:3000/d/alerts'
          - type: button
            text: 'View in Prometheus'
            url: 'http://prometheus:9090/alerts'

templates:
  - '/etc/alertmanager/template/*.tmpl' 